---
AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - '*.gemspec'
    - '*.feature'
    - '**/vendor/**/*'
Metrics/AbcSize:
  Max: 40
Metrics/ClassLength:
  Max: 500
Metrics/MethodLength:
  Max: 30
Layout/LineLength:
  Max: 160
Style/ClassAndModuleChildren:
  Enabled: false
